spring:
  application.name: spring-kotlin-jwt
  datasource:
    url: jdbc:mariadb://localhost:3306/{????????}
    username: ?? ??
    password: ????
    driver-class-name: org.mariadb.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  shutdown: graceful
  port: 1000

app:
  jwt:
    secret: ??? ?
    access_expires_after: 86400000
    refresh_expires_after: 172800000
    issuer: kjone