spring:
  application.name: spring-kotlin-jwt
  datasource:
    url: jdbc:mariadb://localhost:3306/auth_test
    username: root
    password: 7590sa12
    driver-class-name: org.mariadb.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  shutdown: graceful
  port: 1000

app:
  jwt:
    secret: z6woqJSv+SruBJyZbfA31WO7xCb/2Z9Tn93+/wt04ycVVFiN6xTqAwCWrpOfCeyuaGsTAxJcRZ3snBuclwKRjg==
    access_expires_after: 86400000
    refresh_expires_after: 172800000
    issuer: kjone